language: php
php:
    - 8.0
    - 8.1
    
env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        include:
            - php; 8.1
              dist: xenial
        
install:
    - travis_retry composer update ${COMPOSER_FLAGS}
    
script:
  - vendor/bin/phpunit --testdox tests